### ISSUE TITLE
Pastes expiries give SQL exception

### ISSUE THREAD

**Issue by aoiroza** [jonathanj/clj-codetip#11]
When pastes are supposed to expire the below SQL exception happens instead: 

```
Jan 13, 2016 1:32:07 PM clojure.tools.logging$eval1$fn__5 invoke
INFO: {:ssl-client-cert nil, :remote-addr 192.168.10.51, :params {}, :headers {host pastebin.domain.here, accept-language en-US,en;q=0.5, if-modified-since Wed, 03 Jun 2015 12:52:50 GMT, user-agent Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0, accept-encoding gzip, deflate, connection keep-alive, accept image/png,image/*;q=0.8,*/*;q=0.5}, :server-port 80, :content-length nil, :content-type nil, :character-encoding nil, :uri /static/codetip.svg, :server-name pastebin.domain.here, :query-string nil, :body #<HttpInput org.eclipse.jetty.server.HttpInput@32b47030>, :multipart-params {}, :db-conn {:connection #<SQLiteConnection org.sqlite.SQLiteConnection@5c993556>, :connection-uri jdbc:sqlite:codetip.db}, :scheme :http, :request-method :get}
java.sql.SQLException: database connection closed
    at org.sqlite.core.CoreConnection.checkOpen(CoreConnection.java:261)
    at org.sqlite.jdbc3.JDBC3Connection.getAutoCommit(JDBC3Connection.java:140)
    at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:574)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clj_codetip.database$delete_expired_pastes_BANG_.invoke(database.clj:30)
    at clj_codetip.database$_schedule_paste_expiry$fn__12177.invoke(database.clj:37)
    at chime$chime_at$fn__12139$state_machine__10400__auto____12140$fn__12142$fn__12148.invoke(chime.clj:68)
    at clojure.core.async$thread_call$fn__10579$fn__10580.invoke(async.clj:390)
    at clojure.core.async$thread_call$fn__10579.invoke(async.clj:390)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Any insights would be appreciated.

**Comment by jonathanj** [comment]
I'd never noticed this before.

I think the reason for this is that the database connection instance is created in a request and that is reused when scheduling the expiration. I think the solution to this is to only provide the connection URI when scheduling the expiration.

**Comment by jonathanj** [comment]
I think the trickiest part is actually testing this, hopefully I should be able to get a fix out this week.

**Comment by jonathanj** [comment]
Thanks for reporting this, @aoiroza. It should be resolved in master now.

**Comment by aoiroza** [comment]
Thanks for the quick response.
Tested the fix and paste expired.
